### ISSUE TITLE
Adição de Informações sobre os Jogos

### ISSUE THREAD

**Issue by andretoshiake** [andretoshiake/jamaicadoaltotiete#2]
Na página de "Jogos", quando clicamos no botão "Veja Mais.." de cada jogo, hoje conseguimos ver apenas os eventos de cada jogo, (Gols e Assistências). Os quais são cadastrados na página de cada jogo.

Seria interessante poder visualizar mais informações nessa pop-up como exemplo, fotos/videos, texto/resumo/escalação sobre cada jogo.
Podendo ser feito em abas de forma que fique agradável visualmente, separando em 03 abas, 
1. Estatísticas (hoje temos gols e assistências, talvez exibir também as defesas; 
2. Resumo do Jogo/Texto/Texto corrido
3. Mídias (podendo ser fotos/videos em alguns jogos player com vídeo do Youtube) 

Para cadastrar essas informações podem ser adicionados campos na própria página de criação dos jogos. 
Para a primeira aba de estatísticas já temos os campos sendo cadastrados
Para a segunda aba de Resumo do jogo poderia ser um campo de texto livre
Para a terceira aba campos semelhantes ao de cadastro de jogador onde é possível acrescentar uma quantidade x de fotos e até um vídeo. Em alguns jogos os videos estarão disponíveis no Youtube, com isso apenas um campo para colocar a URL do vídeo no Youtube que será exibido como player na página.

**Comment by wilsonmoura** [comment]
@andretoshiake ajustes realizados. Seguem imagens para explicar como foi feita a implementação:

1. Aba Estatísticas

![screenshot-localhost-2023 09 09-21_42_12](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/f2cd750e-a6a5-4bb4-b787-d253f0acb7d0)

2. Aba Detalhes

![screenshot-localhost-2023 09 09-21_41_33](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/27acfc0b-aaeb-4aca-bc95-d8ea648351d9)

3. Aba Mídias*
![screenshot-localhost-2023 09 09-21_40_44](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/24f233b9-c69e-4aed-b93f-8bceefb1f175)

Favor validar essa atividade para que possamos atualizar o site atual e, caso necessário, informar possíveis ajustes nessa implementação.

*Na aba Mídias, é possível exibir 5 fotos e 1 vídeo.

**Comment by andretoshiake** [comment]
Perfeito! Por gentileza dar sequência para o site.
