### ISSUE TITLE
Remover "Patrocinadores do Site"

### ISSUE THREAD

**Issue by andretoshiake** [andretoshiake/jamaicadoaltotiete#3]
Em todas as páginas, nos rodapés, podemos ver os logos da Bonifaz, Cariri e Salvatori.. Esses logos devem ser removidos.. porém gostaria de manter o degradê do amarelo até o verde do jeito que está hoje.. talvez subindo os logos das redes sociais..

**Comment by wilsonmoura** [comment]
@andretoshiake ajustes realizados. Segue imagem do footer para validar:

![screenshot-localhost-2023 07 15-04_15_59](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/7a347422-ef0f-4e2e-baf1-70a1abb790b6)

**Comment by wilsonmoura** [comment]
Definido cor de fundo no tom verde gradiente.
