### ISSUE TITLE
Criação da aba "Conquistas"

### ISSUE THREAD

**Issue by andretoshiake** [andretoshiake/jamaicadoaltotiete#4]
Na página de cada jogador acrescentar uma nova aba chamada "Conquistas" 
Nessa nova aba teremos a criação das medalhas que cada jogador irá adquirindo conforme participa dos jogos/rachões e também a listagem dos prêmios que os jogadores forem conquistando nas premiações de final de ano.
Essa nova aba será dividida em 3 partes, sendo elas:
Medalhas
1. As medalhas referentes aos Amistosos: (Jogos, Gols, Assistências, Defesas)
2. As medalhas referentes aos Rachões: (Jogos, Gols, Assistências, Defesas)
Prêmios
3. Prêmios adquiridos no final de ano após votação

**Comment by wilsonmoura** [comment]
@andretoshiake ajustes realizados. Segue imagem para explicar como foi feita a implementação:

![reward](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/c92530de-9744-4b99-83c8-bdd9c60f826f)

Favor validar essa atividade para que possamos atualizar o site atual e, caso necessário, informar possíveis ajustes nessa implementação.

**Comment by andretoshiake** [comment]
Ficou faltando apenas um espaço para as conquistas do critério "Defesas".. acrescentando esse quarto e último critério podemos dar sequência
