### ISSUE TITLE
Alterações na página do Rachão

### ISSUE THREAD

**Issue by andretoshiake** [andretoshiake/jamaicadoaltotiete#5]
Logo após o texto sobre o rachão, habilitar um novo bloco similar ao da página de Jogos onde será possível ver o resultado de cada rachão. A estrutura será a mesma da nova página de jogos onde será possível clicar em uma opção de "Ver mais..." que será exibido as informações de cada rachão (gols, assistências, defesas, textos, fotos, videos). Todas essas informações já estão cadastradas. Os jogos sempre serão "Amarelo x Azul" pois são as cores dos coletes que utilizamos.

No bloco seguinte temos a tabela com as estatísticas gerais do rachão, acrescentar formas de filtrar essas informações como: ordenar por ordem crescente/decrescente os dados: jogos, gols, assistências e defesas.. e de alguma forma conseguir separar os dados por ano.

**Comment by wilsonmoura** [comment]
@andretoshiake ajustes realizados. Seguem imagens para explicar como foi feita a implementação:

1. Criar submenu no menu Jogos com duas opções: Oficiais e Rachão

![screenshot-localhost-2023 09 08-18_12_03](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/5264d25e-822a-42f2-b932-0dde4e3b623d)

2. Acessar o submenu Rachão

![screenshot-localhost-2023 09 08-18_13_12](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/54e13589-edb7-47cb-9826-192d7e95fea9)

Favor validar essa atividade para que possamos atualizar o site atual e, caso necessário, informar possíveis ajustes nessa implementação.
