### ISSUE TITLE
Alteração de Cabeçalho

### ISSUE THREAD

**Issue by andretoshiake** [andretoshiake/jamaicadoaltotiete#8]
Deverá ser criado um menu adicional para dividir as opções do site. A ideia é dividir entre o menu principal (Home, JAT, Elenco Principal, Rachão e Jogos) e o menu secundário (Blog, Contato, Loja).

Com isso o elenco principal e o rachão serão separados (antes eram dentro do link "Elencos") e será adicionado o link para a Loja do Jamaica

A ideia de layout é utilizar uma faixa preta (para o menu secundário) logo acima da barra verde (menu principal) usando como ideia o site do Manchester United.

**Comment by andretoshiake** [comment]
![menu](https://github.com/andretoshiake/jamaicadoaltotiete/assets/93218552/6a64c4ec-a682-4fc6-86ce-aa950232f75d)

**Comment by wilsonmoura** [comment]
Menu principal:
- Home
- JAT
- Elenco
- Rachão
- Jogos

Menu secundário:
- Blog
- Loja
- Contato

**Comment by wilsonmoura** [comment]
@andretoshiake ajustes realizados. Seguem imagens para definição da cor de fundo do menu secundário:

![screenshot-localhost-2023 07 15-03_31_49](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/be454c66-79f0-4e02-beab-2d9011fca1e9)

![screenshot-localhost-2023 07 15-03_34_37](https://github.com/andretoshiake/jamaicadoaltotiete/assets/3779520/dae5d39c-2ca3-4edc-8b29-37c33f25cf05)

**Comment by wilsonmoura** [comment]
Definido cor de fundo do menu secundário no tom verde.
